import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-sans text-center text-gray-800 bg-gradient-to-br from-blue-300 to-pink-300">
      
        {children}
      </body>
    </html>
  );
}
